"""Unit tests for the telemetry simulator foundation."""

from backend.models.telemetry import normalize_event
from simulator.scenarios.base import ScenarioConfig
from simulator.scenarios.normal import NormalTrafficScenario


def test_normal_simulator_deterministic_output():
    """Verify that identical seeds produce identical synthetic events."""
    config1 = ScenarioConfig(seed=42, count=20)
    scenario1 = NormalTrafficScenario(config1)
    events1 = scenario1.generate()

    config2 = ScenarioConfig(seed=42, count=20)
    scenario2 = NormalTrafficScenario(config2)
    events2 = scenario2.generate()

    assert len(events1) == 20
    assert len(events2) == 20
    assert events1 == events2, "Simulator outputs with same seed must be identical"


def test_normal_simulator_different_seeds_vary():
    """Verify different seeds produce different event sequences."""
    config1 = ScenarioConfig(seed=42, count=20)
    events1 = NormalTrafficScenario(config1).generate()

    config2 = ScenarioConfig(seed=999, count=20)
    events2 = NormalTrafficScenario(config2).generate()

    assert events1 != events2, "Simulator outputs with different seeds should vary"


def test_normal_simulator_events_conform_to_canonical_schema():
    """Verify every event generated by the simulator normalizes cleanly into CanonicalEvent."""
    config = ScenarioConfig(seed=12345, count=50)
    scenario = NormalTrafficScenario(config)
    events = scenario.generate()

    assert len(events) == 50
    for raw_event in events:
        canonical = normalize_event(raw_event)
        assert canonical.event_id is not None
        assert canonical.source_type in ["AUTH", "NETWORK", "SYSTEM"]
        assert canonical.result is not None
